# Generated by Django 2.1 on 2018-08-21 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=100)),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('permission_level', models.IntegerField(default=1, verbose_name='permission')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.RemoveField(
            model_name='personlocation',
            name='date_added',
        ),
        migrations.AddField(
            model_name='document',
            name='date_added',
            field=models.DateTimeField(default=None, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='document',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
            preserve_default=False,
        ),
    ]
