# Generated by Django 2.1 on 2018-09-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180821_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
