# Generated by Django 2.1 on 2018-09-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180912_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place_name',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
