# Generated by Django 2.1 on 2018-09-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place_name',
        ),
        migrations.AddField(
            model_name='location',
            name='place_name_both',
            field=models.CharField(default='Unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='place_name_receiver',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='location',
            name='place_name_sender',
            field=models.CharField(default='Unknown', max_length=64),
        ),
    ]
