# Generated by Django 2.1 on 2018-09-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180923_1122'),
        ('db', '0003_auto_20180922_1750'),
    ]

    operations = [
    ]
