# Generated by Django 2.1 on 2018-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180908_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_written',
            field=models.CharField(max_length=150),
        ),
    ]
