# Generated by Django 2.1 on 2018-09-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_merge_20180923_2056'),
        ('db', '0004_auto_20180923_1856'),
    ]

    operations = [
    ]
