# Generated by Django 2.1 on 2018-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_merge_20180923_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(max_length=64),
        ),
    ]
