# Generated by Django 2.1 on 2018-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180908_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place_name_receiver',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_name_both',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_name_sender',
        ),
        migrations.AlterField(
            model_name='document',
            name='date_written',
            field=models.DateTimeField(verbose_name='date written'),
        ),
    ]
