# Generated by Django 2.1 on 2018-10-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20180923_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privileges',
            options={'managed': False, 'permissions': (('can_upload', 'User has the ability to upload a document.'), ('can_search', 'User has the ability to search for documents.'), ('can_edit', 'User has the ability to edit document data.'))},
        ),
    ]
