# Generated by Django 2.1 on 2018-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_merge_20181015_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.CharField(default='Nothing', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
