# Generated by Django 2.1 on 2018-10-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_merge_20181023_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.CharField(max_length=3000),
        ),
    ]
